name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore apt lists and cache
        id: cache-apt
        uses: actions/cache/restore@v4
        with:
          path: |
            apt-cache
            apt-lists
          key: >-
            os-${{ matrix.os }}
            apt-${{ hashFiles('.github/apt.txt') }}
          restore-keys: >-
            os-${{ matrix.os }}
            apt-

      - name: Restore apt lists to original location
        run: |-
          sudo_prefix=""
          test -z "$ACT" && sudo_prefix=sudo
          $sudo_prefix rm -rf /var/lib/apt/lists || true
          $sudo_prefix mv apt-lists /var/lib/apt/lists || echo No cache

      - name: apt update
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |-
          sudo_prefix=""
          test -z "$ACT" && sudo_prefix=sudo
          rm /etc/apt/apt.conf.d/docker* || true
          time $sudo_prefix apt update
          $sudo_prefix cp -r /var/lib/apt/lists apt-lists
          $sudo_prefix chown -R $UID:$UID apt-lists

      - name: apt install
        run: |-
          flags=""
          sudo_prefix=""
          test "${{ steps.cache-apt.outputs.cache-hit }}" = 'true' \
              && flags="--no-download"
          test -z "$ACT" && sudo_prefix=sudo
          rm /etc/apt/apt.conf.d/docker* || true

          time $sudo_prefix rm -rf /var/cache/apt || true
          time $sudo_prefix mv apt-cache /var/cache/apt || echo No cache
          time $sudo_prefix apt-get \
              -o APT::Keep-Downloaded-Packages=true \
              install \
              $flags \
              --no-install-recommends \
              --no-install-suggests -y $(grep -v '#' .github/apt.txt)
          $sudo_prefix cp -r /var/cache/apt apt-cache
          $sudo_prefix chown -R $UID:$UID apt-cache

      - name: Cache apt packages
        uses: actions/cache/save@v4
        with:
          path: |
            apt-cache
            apt-lists
          key: >-
            os-${{ matrix.os }}
            apt-${{ hashFiles('.github/apt.txt') }}
          restore-keys: >-
            os-${{ matrix.os }}
            apt-
