# act -j compile --use-new-action-cache --action-offline-mode

# todo(artifacts): /root/.emacs.d/elpa,elpaca; chown -R 1000:1000, tgz, sign
name: CI

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

jobs:
  compile:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        emacs: [
          # '27.1', '27.2',
          # '28.1',
          # '28.2',
          # '29.1', '29.2',
          '29.3',
          # 'snapshot'
        ]

    container:
      image: silex/emacs:${{ matrix.emacs }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure clean byte-compilation
        run: |
          set -e
          emacs --batch --quick \
              --directory . \
              --load <(echo "(setq byte-compile-error-on-warn t)") \
              --eval '(unless (byte-compile-file ".emacs") (kill-emacs 1))'
